/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/fFMXM4jmNrd
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Prata } from 'next/font/google'

prata({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";
import Image from "next/image";
import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  ResizablePanelGroup,
  ResizablePanel,
  ResizableHandle,
} from "@/components/ui/resizable";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
export function MainPage() {
  const [resizeValue, setResizeValue] = useState(50);
  return (
    <div className="flex flex-col min-h-dvh bg-[url('/background.png')] bg-bottom bg-repeat-x ">
      <header className="px-4 lg:px-6 h-14 flex items-center bg-[#1E0018]">
        <Link
          href="#"
          className="flex items-center justify-center"
          prefetch={false}
        >
          <span className="font-vcomics text-white">VCOMICS</span>
        </Link>
        <div className="ml-auto">
          <Link
            href="#"
            className="text-white hover:underline underline-offset-4"
            prefetch={false}
          >
            <UserIcon className="size-6" />
          </Link>
        </div>
      </header>
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32">
          <div className="px-4 md:px-6 space-y-10 xl:space-y-16">
            <div className="grid mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
              <div className="flex flex-col items-start justify-center">
                <h1 className="text-[#1E0018] text-4xl md:text-5xl lg:text-6xl font-adventure uppercase">
                  Tell your
                </h1>
                <h1 className="text-[#1E0018] text-4xl md:text-5xl lg:text-6xl font-adventure uppercase">
                  story through
                </h1>
                <h1 className="text-[#1E0018] text-4xl md:text-5xl lg:text-6xl font-adventure uppercase">
                  comics
                </h1>

                <p className=" text-[#1E0018] md:text-xl font-extralight">
                  VCOMICS - AI that turns your ideas and photos into
                  personalized comics, bringing your story to life
                </p>
                <Link href="/upload-photo" className="w-full">
                  <Button className="mt-6 bg-[#BB1215] border-[#1E0018] text-white font-adventure uppercase px-6 py-3 w-full">
                    START
                  </Button>
                </Link>
              </div>
              <div className="flex flex-col items-center justify-center">
                <ResizablePanelGroup
                  direction="horizontal"
                  className="w-full h-[400px]"
                >
                  <ResizablePanel defaultSize={resizeValue}>
                    <div className="w-full h-full rounded-lg relative">
                      <Image
                        src="/mainpage.jpg"
                        width={400}
                        height={400}
                        alt="After image"
                        className="w-full h-full object-cover rounded-lg aspect-square"
                      />
                      <div className="absolute top-0 right-0 bg-[#ffff00] px-2 py-1 text-xs">
                        drag
                      </div>
                    </div>
                  </ResizablePanel>
                  <ResizableHandle withHandle />
                  <ResizablePanel defaultSize={100 - resizeValue}>
                    <img
                      src="/mainpage2.png"
                      width={400}
                      height={400}
                      alt="After image"
                      className="w-full h-full object-cover rounded-lg aspect-square"
                    />
                  </ResizablePanel>
                </ResizablePanelGroup>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid gap-6 px-4 md:px-6 grid-cols-1 md:grid-cols-4">
            <Card>
              <CardContent className="p-0">
                <img
                  src="/panel-7.jpeg"
                  width={400}
                  height={400}
                  alt="Comic Cover"
                  className="object-cover aspect-square rounded-t-md"
                />
              </CardContent>
              <CardFooter className="px-4 py-2 flex flex-col">
                <div className="font-medium">Парк</div>
                <div className="text-sm text-muted-foreground">
                  Alan Moore, Dave Gibbons
                </div>
              </CardFooter>
            </Card>
            <Card>
              <CardContent className="p-0">
                <img
                  src="https://jzfstrhyaxuupvfyibws.supabase.co/storage/v1/object/public/vcomics/panel-7-1721936521526"
                  width={400}
                  height={400}
                  alt="Comic Cover"
                  className="object-cover aspect-square rounded-t-md"
                />
              </CardContent>
              <CardFooter className="px-4 py-2 flex flex-col">
                <div className="font-medium">Garden</div>
                <div className="text-sm text-muted-foreground">
                  Art Spiegelman
                </div>
              </CardFooter>
            </Card>
            <Card>
              <CardContent className="p-0">
                <img
                  src="https://jzfstrhyaxuupvfyibws.supabase.co/storage/v1/object/public/vcomics/panel-3-1721940428277"
                  width={400}
                  height={400}
                  alt="Comic Cover"
                  className="object-cover aspect-square rounded-t-md"
                />
              </CardContent>
              <CardFooter className="px-4 py-2 flex flex-col">
                <div className="font-medium">Honey</div>
                <div className="text-sm text-muted-foreground">
                  Alicia
                </div>
              </CardFooter>
            </Card>
            <Card>
              <CardContent className="p-0">
                <img
                  src="https://jzfstrhyaxuupvfyibws.supabase.co/storage/v1/object/public/vcomics/panel-8-1722183635310"
                  width={400}
                  height={400}
                  alt="Comic Cover"
                  className="object-cover aspect-square rounded-t-md"
                />
              </CardContent>
              <CardFooter className="px-4 py-2 flex flex-col">
                <div className="font-medium">Мой корги по имени Сэм</div>
                <div className="text-sm text-muted-foreground">
                  Neil Gaiman, Sam Kieth
                </div>
              </CardFooter>
            </Card>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6">
        <p className="text-xs text-muted-foreground">
          &copy; 2024 VCOMICS. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}
          >
            Terms of Service
          </Link>
          <Link
            href="#"
            className="text-xs hover:underline underline-offset-4"
            prefetch={false}
          >
            Privacy
          </Link>
        </nav>
      </footer>
      {/* <div className="absolute bottom-0 left-0 w-full h-32 bg-gradient-to-t from-[#f5f5f5] to-transparent" /> */}
    </div>
  );
}

function BookOpenIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
      <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
    </svg>
  );
}

function UserIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}

function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
